name: polymer_time_picker_example
description: Original project https://github.com/bendavis78/paper-date-picker
version: 0.0.3
homepage: https://github.com/olimou/dart-polymer-paper-date-picker
author: Emerson Moura <olimou@gmail.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  polymer: "^1.0.0-rc"
  polymer_elements: "^1.0.0-rc"
  web_components: ^0.12.0
  polymer_time_picker:
    path: ../

dev_dependencies:
  angular2: ^3.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1